using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Security.Cryptography;

namespace JundotPackageBuilder;

/// <summary>
/// Uploads a built package (zip + manifest) to a GitHub Release.
///
/// Workflow:
///   1. Create or find a GitHub Release (by tag)
///   2. Upload the zip as a release asset
///   3. Backfill `download_url` into the manifest
///   4. Re-upload the updated manifest
///
/// Supports a dry-run mode that prints what would happen without
/// making any network calls.
/// </summary>
public class GitHubReleasePublisher
{
    private readonly PublishConfig _config;
    private readonly HttpClient _http;
    private readonly string _repoRoot;

    public GitHubReleasePublisher(string repoRoot, PublishConfig config)
    {
        _repoRoot = repoRoot;
        _config = config;

        _http = new HttpClient
        {
            DefaultRequestHeaders =
            {
                { "User-Agent", "JundotPackageBuilder-Publisher/1.0" },
                { "Accept", "application/vnd.github+json" },
                { "X-GitHub-Api-Version", "2022-11-28" }
            },
            Timeout = TimeSpan.FromMinutes(5)
        };

        var token = config.GetToken();
        if (!string.IsNullOrEmpty(token))
        {
            _http.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", token);
        }
    }

    // ── Public API ──────────────────────────────────────────────

    /// <summary>
    /// Publish a built package to GitHub Releases.
    /// If <paramref name="changeEvaluationPath"/> is provided and AI
    /// summarization is enabled, the release body will be generated by
    /// the configured MiMo-Code-jundot endpoint automatically.
    /// </summary>
    /// <returns>True on success, false on failure.</returns>
    public async Task<bool> PublishAsync(
        string packageName,
        string version,
        string zipPath,
        string manifestPath,
        string? platform = null,
        string? arch = null,
        string? changeEvaluationPath = null,
        string? aiOverrideBody = null,
        CancellationToken ct = default)
    {
        return await PublishManyAsync(
            new[]
            {
                (packageName, version, zipPath, manifestPath,
                    platform ?? "win",
                    arch ?? "x64",
                    changeEvaluationPath ?? "")
            },
            aiOverrideBody,
            ct);
    }

    /// <summary>
    /// Publish multiple built packages that share the same version
    /// under a single GitHub Release (one tag). Each build gets an
    /// individual zip + manifest asset, uniquely named by platform/arch.
    ///
    /// The AI summary is generated once using the combined metadata of
    /// all packages; subsequent packages reuse the same release body.
    /// </summary>
    /// <returns>True when all packages publish successfully.</returns>
    public async Task<bool> PublishManyAsync(
        IEnumerable<(string PackageName, string Version, string ZipPath, string ManifestPath, string Platform, string Arch, string ChangeEvaluationPath)> packages,
        string? aiOverrideBody = null,
        CancellationToken ct = default)
    {
        var list = packages.ToList();
        if (list.Count == 0)
        {
            LogError("No packages to publish.");
            return false;
        }

        // Validate files + config once
        foreach (var p in list)
        {
            if (!File.Exists(p.ZipPath))
            {
                LogError($"Zip file not found: {p.ZipPath}");
                return false;
            }
            if (!File.Exists(p.ManifestPath))
            {
                LogError($"Manifest file not found: {p.ManifestPath}");
                return false;
            }
        }

        if (_config.DryRun)
        {
            foreach (var p in list)
                DryRunPublish(p.PackageName, p.Version, p.ZipPath, p.ManifestPath);
            return true;
        }

        var token = _config.GetToken();
        if (string.IsNullOrEmpty(token))
        {
            LogError($"GitHub token not set. Set the {_config.TokenEnvVar} environment variable.");
            return false;
        }

        try
        {
            // ── Step 0: Generate AI summary ONCE using combined context ──
            var firstPkg = list[0];
            if (!string.IsNullOrWhiteSpace(_config.ReleaseBody) &&
                !ReleaseBodyMatchesVersion(_config.ReleaseBody, firstPkg.Version))
            {
                LogInfo($"Ignoring stale saved release body because it does not mention version {firstPkg.Version}.");
                _config.ReleaseBody = "";
            }

            string? aiBody = aiOverrideBody;
            if (!string.IsNullOrWhiteSpace(aiBody) && !ReleaseBodyMatchesVersion(aiBody, firstPkg.Version))
            {
                LogInfo($"Ignoring override release body because it does not mention version {firstPkg.Version}.");
                aiBody = null;
            }

            if (string.IsNullOrEmpty(aiBody) && _config.UseAiSummary)
            {
                LogInfo($"Generating AI release summary for {list.Count} package(s)...");

                var combinedPackageNames = string.Join(", ", list.Select(p => p.PackageName));
                var changeEvaluationPath = EnsureChangeEvaluationReport(firstPkg, forceRegenerate: true);

                // Prefer the first package's change evaluation / manifest as input to the AI.
                var summarizer = new AiReleaseSummarizer(_config);
                summarizer.LogMessage += (s, e) => LogInfo(e);

                aiBody = await summarizer.SummarizeAsync(
                    firstPkg.Version,
                    combinedPackageNames,
                    changeEvaluationPath,
                    firstPkg.ManifestPath,
                    _config.Changelog ?? "",
                    ct);

                if (!string.IsNullOrEmpty(aiBody) && ReleaseBodyMatchesVersion(aiBody, firstPkg.Version))
                {
                    _config.ReleaseBody = aiBody;
                    LogInfo("Release body updated with AI summary.");
                }
                else if (!string.IsNullOrEmpty(aiBody))
                {
                    LogInfo($"AI summary did not mention version {firstPkg.Version}; discarding it to avoid publishing stale notes.");
                    aiBody = null;
                    _config.ReleaseBody = "";
                }
                else
                {
                    LogInfo("AI summary unavailable; using generated fallback release body.");
                    _config.ReleaseBody = BuildFallbackReleaseBody(firstPkg.Version, list);
                }
            }
            else if (!string.IsNullOrEmpty(aiBody))
            {
                _config.ReleaseBody = aiBody;
            }

            // ── Step 1: Find or create the shared release ──
            var releaseTag = string.IsNullOrEmpty(_config.ReleaseTag)
                ? $"v{firstPkg.Version}"
                : _config.ReleaseTag;

            var releaseName = string.IsNullOrEmpty(_config.ReleaseName)
                ? $"Jundot {firstPkg.Version}"
                : _config.ReleaseName;

            LogInfo($"Publishing {list.Count} package(s) to GitHub Releases (tag: {releaseTag})...");
            LogInfo($"Release flags: draft={_config.Draft}, prerelease={_config.Prerelease}, make_latest=github-default");

            var release = await FindOrCreateReleaseAsync(releaseTag, releaseName, ct);
            if (release == null)
            {
                LogError("Failed to find or create release.");
                return false;
            }

            var uploadUrl = release.UploadUrl.Replace("{?name,label}", "");
            LogInfo($"Release ID: {release.Id}, upload URL: {uploadUrl}");

            // ── Step 2: Upload each package as distinct assets ──
            var allOk = true;

            // Collect per-platform info for the unified update-manifest.json
            var perPlatform = new List<(
                string packageName, string platform, string arch,
                string zipUrl, string manifestUrl, long size, string sha256
            )>();

            foreach (var (packageName, _, zipPath, manifestPath, platform, arch, _) in list)
            {
                // Build unique asset names that won't collide across platforms/archs
                var platformArch = string.IsNullOrEmpty(platform)
                    ? ""
                    : $"{platform}-{arch ?? "any"}";

                var defaultZipName = Path.GetFileName(zipPath);
                // If the zip name doesn't already contain platform/arch info, embed it
                var zipAssetName = ContainsPlatformArch(defaultZipName, platform, arch)
                    ? defaultZipName
                    : BuildAssetName(packageName, platformArch, "zip");

                var manifestAssetName = BuildAssetName(packageName, platformArch, "manifest.json");

                LogInfo($"── Publishing {packageName} ({platformArch ?? "default"})");
                LogInfo($"   zip asset:     {zipAssetName}");
                LogInfo($"   manifest asset:{manifestAssetName}");

                // --- Precompute: read size + hash + original manifest fields ---
                long zipSize = 0;
                string zipSha256 = "";
                try
                {
                    var fi = new FileInfo(zipPath);
                    zipSize = fi.Length;
                    using var stream = File.OpenRead(zipPath);
                    using var sha = SHA256.Create();
                    var hash = sha.ComputeHash(stream);
                    zipSha256 = BitConverter.ToString(hash).Replace("-", "").ToLowerInvariant();
                }
                catch (Exception ex)
                {
                    LogInfo($"   (could not precompute size/sha256 from zip: {ex.Message})");
                }

                // Upload zip
                var zipDownloadUrl = await UploadAssetAsync(
                    uploadUrl, zipPath, zipAssetName, "application/zip", ct,
                    releaseId: release.Id);

                if (string.IsNullOrEmpty(zipDownloadUrl))
                {
                    LogError($"Failed to upload zip asset for {packageName}.");
                    allOk = false;
                    continue;
                }
                LogInfo($"   Zip uploaded: {zipDownloadUrl}");

                string? manifestDownloadUrl = null;

                // Backfill download_url into manifest, then upload
                try
                {
                    var manifestJson = await File.ReadAllTextAsync(manifestPath, ct);
                    var manifestNode = JsonNode.Parse(manifestJson);
                    if (manifestNode != null)
                    {
                        manifestNode["download_url"] = zipDownloadUrl;
                        manifestNode["release_date"] = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");
                        manifestNode["changelog"] = _config.Changelog ?? "";
                        manifestNode["mandatory"] = _config.Mandatory;
                        if (manifestNode["grayscale"] is JsonObject gs)
                        {
                            gs["percentage"] = _config.GrayscalePercentage;
                            gs["enabled"] = _config.GrayscalePercentage < 100;
                        }

                        var updatedManifest = manifestNode.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
                        var tempManifest = Path.Combine(Path.GetTempPath(), $"jundot-{packageName}-{Guid.NewGuid():N}.manifest.json");
                        await File.WriteAllTextAsync(tempManifest, updatedManifest, ct);

                        manifestDownloadUrl = await UploadAssetAsync(
                            uploadUrl, tempManifest, manifestAssetName, "application/json", ct,
                            releaseId: release.Id);

                        if (!string.IsNullOrEmpty(manifestDownloadUrl))
                            LogInfo($"   Manifest updated: {manifestDownloadUrl}");
                        else
                            LogError($"   Failed to upload manifest for {packageName}.");

                        try { File.Delete(tempManifest); } catch { }
                    }
                }
                catch (Exception ex)
                {
                    LogError($"Failed to process manifest for {packageName}: {ex.Message}");
                    allOk = false;
                }

                perPlatform.Add((
                    packageName, platform ?? "unknown", arch ?? "x86_64",
                    zipDownloadUrl, manifestDownloadUrl ?? "", zipSize, zipSha256));
            }

            // ── Step 3: Generate and upload unified update-manifest.json ──
            try
            {
                LogInfo("── Generating unified update-manifest.json for the engine UpdateManager");
                var unifiedBasePkg = list[0];
                var firstManifestPath = unifiedBasePkg.ManifestPath;

                var root = new System.Text.Json.Nodes.JsonObject();

                // Use the first package's manifest as the base (version / changelog / grayscale / etc.)
                if (File.Exists(firstManifestPath))
                {
                    var baseJson = await File.ReadAllTextAsync(firstManifestPath, ct);
                    var baseNode = JsonNode.Parse(baseJson);
                    if (baseNode is System.Text.Json.Nodes.JsonObject baseObj)
                    {
                        foreach (var kv in baseObj)
                            root[kv.Key] = kv.Value?.DeepClone();
                    }
                }

                // Override with shared fields
                root["manifest_version"] = "1.1";
                root["release_date"] = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ");
                root["changelog"] = _config.Changelog ?? "";
                root["mandatory"] = _config.Mandatory;
                if (root["grayscale"] is System.Text.Json.Nodes.JsonObject gs2)
                {
                    gs2["percentage"] = _config.GrayscalePercentage;
                    gs2["enabled"] = _config.GrayscalePercentage < 100;
                }

                // Use the first package's primary download URL as a fallback for older engines
                if (perPlatform.Count > 0)
                {
                    var first = perPlatform[0];
                    root["download_url"] = first.zipUrl;
                    root["package_size"] = first.size;
                    root["sha256"] = first.sha256;
                    root["platform"] = first.platform;
                    root["arch"] = first.arch;
                }

                // platform_downloads: list of per-platform download entries
                var downloadsArr = new System.Text.Json.Nodes.JsonArray();
                foreach (var p in perPlatform)
                {
                    var entry = new System.Text.Json.Nodes.JsonObject
                    {
                        ["package_name"] = p.packageName,
                        ["platform"] = p.platform,
                        ["arch"] = p.arch,
                        ["key"] = $"{p.platform}-{p.arch}",
                        ["download_url"] = p.zipUrl,
                        ["manifest_url"] = p.manifestUrl,
                        ["package_size"] = p.size,
                        ["sha256"] = p.sha256,
                    };
                    downloadsArr.Add(entry);
                }
                root["platform_downloads"] = downloadsArr;

                // AI summary → release body / changelog
                if (!string.IsNullOrEmpty(_config.ReleaseBody))
                    root["release_body"] = _config.ReleaseBody;

                var unifiedJson = root.ToJsonString(new JsonSerializerOptions { WriteIndented = true });
                var unifiedPath = Path.Combine(Path.GetTempPath(), $"jundot-update-manifest-{Guid.NewGuid():N}.json");
                await File.WriteAllTextAsync(unifiedPath, unifiedJson, ct);

                var unifiedUrl = await UploadAssetAsync(
                    uploadUrl, unifiedPath, "update-manifest.json", "application/json", ct,
                    releaseId: release.Id);

                if (!string.IsNullOrEmpty(unifiedUrl))
                    LogInfo($"   Unified manifest uploaded: {unifiedUrl}");
                else
                    LogError($"   Failed to upload unified update-manifest.json.");

                try { File.Delete(unifiedPath); } catch { }
            }
            catch (Exception ex)
            {
                LogError($"Failed to generate unified update-manifest.json: {ex.Message}");
                // Not fatal; individual platform manifests were already uploaded.
            }

            LogInfo(allOk
                ? $"All packages published successfully: {release.HtmlUrl}"
                : $"Publish finished with errors. See logs above. {release.HtmlUrl}");
            return allOk;
        }
        catch (OperationCanceledException)
        {
            LogInfo("Publish cancelled.");
            return false;
        }
        catch (Exception ex)
        {
            LogError($"Publish failed: {ex.Message}");
            return false;
        }
    }

    // ── Asset-name helpers ─────────────────────────────────

    private static string BuildAssetName(string packageName, string platformArch, string extension)
    {
        var baseName = string.IsNullOrEmpty(platformArch)
            ? packageName
            : $"{packageName}-{platformArch}";
        return $"{baseName}.{extension.TrimStart('.')}";
    }

    private static bool ContainsPlatformArch(string fileName, string? platform, string? arch)
    {
        if (string.IsNullOrEmpty(fileName)) return false;
        if (!string.IsNullOrEmpty(platform) &&
            fileName.Contains(platform, StringComparison.OrdinalIgnoreCase))
            return true;
        if (!string.IsNullOrEmpty(arch) &&
            fileName.Contains(arch, StringComparison.OrdinalIgnoreCase))
            return true;
        return false;
    }

    // ── Dry-run ─────────────────────────────────────────────────

    private bool DryRunPublish(string packageName, string version, string zipPath, string manifestPath)
    {
        var zipInfo = new FileInfo(zipPath);
        var manifestInfo = new FileInfo(manifestPath);

        LogInfo("=== DRY RUN ===");
        LogInfo($"Package: {packageName}");
        LogInfo($"Version: {version}");
        LogInfo($"Repository: {_config.Owner}/{_config.Repo}");
        LogInfo($"Release Tag: {(string.IsNullOrEmpty(_config.ReleaseTag) ? $"v{version}" : _config.ReleaseTag)}");
        LogInfo($"Draft: {_config.Draft}");
        LogInfo($"Prerelease: {_config.Prerelease}");
        LogInfo($"Grayscale: {_config.GrayscalePercentage}%");
        LogInfo($"Mandatory: {_config.Mandatory}");
        LogInfo($"");
        LogInfo($"Files to upload:");
        LogInfo($"  - {zipPath} ({FormatBytes(zipInfo.Length)})");
        LogInfo($"  - {manifestPath} ({FormatBytes(manifestInfo.Length)})");
        LogInfo($"");
        LogInfo($"Token env var: {_config.TokenEnvVar}");
        LogInfo($"Token set: {(string.IsNullOrEmpty(_config.GetToken()) ? "NO" : "YES")}");
        LogInfo("=== End dry run ===");
        return true;
    }

    // ── GitHub API helpers ──────────────────────────────────────

    private async Task<GitHubRelease?> FindOrCreateReleaseAsync(
        string tag, string name, CancellationToken ct)
    {
        var apiBase = $"https://api.github.com/repos/{_config.Owner}/{_config.Repo}/releases";

        // Try to find an existing release by tag
        try
        {
            var getUrl = $"{apiBase}/tags/{Uri.EscapeDataString(tag)}";
            var response = await _http.GetAsync(getUrl, ct);

            if (response.IsSuccessStatusCode)
            {
                var json = await response.Content.ReadAsStringAsync(ct);
                var existing = JsonSerializer.Deserialize<GitHubRelease>(json);
                if (existing != null)
                    await UpdateReleaseAsync(existing.Id, name, ct);
                return existing;
            }
        }
        catch
        {
            // Not found, will create
        }

        // Create a new release
        var body = _config.ReleaseBody;
        if (string.IsNullOrEmpty(body))
        {
            body = $"Automated build of Jundot {name}.";
        }

        var createPayload = new
        {
            tag_name = tag,
            name,
            body,
            draft = _config.Draft,
            prerelease = _config.Prerelease
        };

        var content = new StringContent(
            JsonSerializer.Serialize(createPayload),
            Encoding.UTF8,
            "application/json");

        var createResponse = await _http.PostAsync(apiBase, content, ct);

        if (!createResponse.IsSuccessStatusCode)
        {
            var errorBody = await createResponse.Content.ReadAsStringAsync(ct);
            LogError($"Failed to create release (HTTP {(int)createResponse.StatusCode}): {errorBody}");
            return null;
        }

        var createJson = await createResponse.Content.ReadAsStringAsync(ct);
        return JsonSerializer.Deserialize<GitHubRelease>(createJson);
    }

    private async Task UpdateReleaseAsync(long releaseId, string name, CancellationToken ct)
    {
        var body = _config.ReleaseBody;
        if (string.IsNullOrEmpty(body))
            body = $"Automated build of Jundot {name}.";

        var payload = new
        {
            name,
            body,
            draft = _config.Draft,
            prerelease = _config.Prerelease
        };

        var content = new StringContent(
            JsonSerializer.Serialize(payload),
            Encoding.UTF8,
            "application/json");

        var url = $"https://api.github.com/repos/{_config.Owner}/{_config.Repo}/releases/{releaseId}";
        var response = await _http.PatchAsync(url, content, ct);
        if (response.IsSuccessStatusCode)
        {
            LogInfo($"Release metadata synchronized. Draft: {_config.Draft}, prerelease: {_config.Prerelease}, make_latest=github-default");
            return;
        }

        var errorBody = await response.Content.ReadAsStringAsync(ct);
        LogInfo($"Could not update existing release metadata (HTTP {(int)response.StatusCode}). If it is already published, GitHub may not allow converting it back to draft. {errorBody}");
    }

    private async Task<string?> UploadAssetAsync(
        string uploadUrl, string filePath, string fileName, string contentType, CancellationToken ct,
        long releaseId = 0)
    {
        var fileBytes = await File.ReadAllBytesAsync(filePath, ct);
        var url = $"{uploadUrl}?name={Uri.EscapeDataString(fileName)}";

        // ── Upload attempt (first pass) ──
        using var content = new ByteArrayContent(fileBytes);
        content.Headers.ContentType = new MediaTypeHeaderValue(contentType);

        var response = await _http.PostAsync(url, content, ct);

        // GitHub returns 422 when an asset with the same name already exists.
        // In that case, try to delete the old asset and re-upload once.
        if ((int)response.StatusCode == 422 && releaseId > 0)
        {
            LogInfo($"Asset '{fileName}' already exists on release #{releaseId}; replacing it...");

            var deleted = await DeleteExistingAssetAsync(releaseId, fileName, ct);
            if (deleted)
                response = await _http.PostAsync(url, content, ct);
        }

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync(ct);
            LogError($"Failed to upload {fileName} (HTTP {(int)response.StatusCode}): {errorBody}");
            return null;
        }

        var json = await response.Content.ReadAsStringAsync(ct);
        var asset = JsonSerializer.Deserialize<GitHubAsset>(json);
        return asset?.BrowserDownloadUrl;
    }

    /// <summary>
    /// List the assets currently attached to a release.
    /// Only needed for UI display/dry run; not required for publishing.
    /// </summary>
    public async Task<List<(long id, string name, string url)>?> ListAssetsAsync(
        long releaseId, CancellationToken ct)
    {
        var apiBase = $"https://api.github.com/repos/{_config.Owner}/{_config.Repo}/releases/{releaseId}/assets";
        try
        {
            var response = await _http.GetAsync(apiBase, ct);
            if (!response.IsSuccessStatusCode) return null;

            var json = await response.Content.ReadAsStringAsync(ct);
            var list = JsonSerializer.Deserialize<List<GitHubAsset>>(json);
            return list?.Select(a => (a.Id, a.Name, a.BrowserDownloadUrl)).ToList();
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// Verify the configured GitHub token works and can access the target repository.
    /// Hits two endpoints:
    ///   GET https://api.github.com/user         (confirms token is valid)
    ///   GET https://api.github.com/repos/o/r    (confirms repo visibility + permissions)
    /// Returns (ok, human-readable message).
    /// </summary>
    public async Task<(bool ok, string message)> ValidateTokenAsync(CancellationToken ct)
    {
        var token = _config.GetToken();
        if (string.IsNullOrEmpty(token))
            return (false, "No GitHub token configured. Either fill in the 'GitHub Token' field in the Advanced tab, or set the environment variable '" + _config.TokenEnvVar + "'.");

        // 1) Check the token itself by reading the authenticated user
        try
        {
            var userResp = await _http.GetAsync("https://api.github.com/user", ct);
            if (!userResp.IsSuccessStatusCode)
            {
                var err = await userResp.Content.ReadAsStringAsync(ct);
                return (false, $"Token rejected by GitHub (HTTP {(int)userResp.StatusCode}). {err}");
            }

            var userJson = await userResp.Content.ReadAsStringAsync(ct);
            var user = JsonSerializer.Deserialize<System.Text.Json.Nodes.JsonObject>(userJson);
            var login = user?["login"]?.GetValue<string>() ?? "(unknown)";

            // 2) Check the repository is reachable with this token
            var repoUrl = $"https://api.github.com/repos/{_config.Owner}/{_config.Repo}";
            var repoResp = await _http.GetAsync(repoUrl, ct);
            if (!repoResp.IsSuccessStatusCode)
            {
                var err = await repoResp.Content.ReadAsStringAsync(ct);
                return (false, $"Token valid as '{login}', but repo '{_config.Owner}/{_config.Repo}' is not reachable (HTTP {(int)repoResp.StatusCode}). {err}");
            }

            var repoJson = await repoResp.Content.ReadAsStringAsync(ct);
            var repo = JsonSerializer.Deserialize<System.Text.Json.Nodes.JsonObject>(repoJson);
            var fullName = repo?["full_name"]?.GetValue<string>() ?? $"{_config.Owner}/{_config.Repo}";

            var scopes = "";
            if (repoResp.Headers.TryGetValues("X-OAuth-Scopes", out var values))
                scopes = string.Join(", ", values);

            // We look for 'repo' scope for creating releases + uploading assets.
            var hasRepoScope = scopes.Split(',').Select(s => s.Trim()).Contains("repo", StringComparer.OrdinalIgnoreCase)
                               || scopes.Split(',').Select(s => s.Trim()).Contains("public_repo", StringComparer.OrdinalIgnoreCase);

            var hint = hasRepoScope ? "" : " (warning: 'repo' scope not found — release publish may fail)";
            return (true, $"Authenticated as '{login}' → repo '{fullName}' reachable. Scopes: {scopes}{hint}");
        }
        catch (HttpRequestException hex)
        {
            return (false, $"Network error: {hex.Message}");
        }
        catch (Exception ex)
        {
            return (false, $"Unexpected error: {ex.Message}");
        }
    }

    /// <summary>
    /// Delete an existing release asset by name so a replacement can be uploaded.
    /// Returns true if anything was deleted.
    /// </summary>
    private async Task<bool> DeleteExistingAssetAsync(long releaseId, string assetName, CancellationToken ct)
    {
        // Step 1: list assets and find the one matching the target name
        var apiBase = $"https://api.github.com/repos/{_config.Owner}/{_config.Repo}/releases/{releaseId}/assets";
        List<GitHubAsset>? assets = null;
        try
        {
            var listResp = await _http.GetAsync(apiBase, ct);
            if (listResp.IsSuccessStatusCode)
            {
                var listJson = await listResp.Content.ReadAsStringAsync(ct);
                assets = JsonSerializer.Deserialize<List<GitHubAsset>>(listJson);
            }
        }
        catch
        {
            return false;
        }

        if (assets == null) return false;

        var matches = assets.Where(a =>
            string.Equals(a.Name, assetName, StringComparison.OrdinalIgnoreCase)).ToList();

        if (matches.Count == 0) return false;

        // Step 2: delete each match
        var anyDeleted = false;
        foreach (var match in matches)
        {
            try
            {
                var delResp = await _http.DeleteAsync(
                    $"https://api.github.com/repos/{_config.Owner}/{_config.Repo}/releases/assets/{match.Id}", ct);
                if (delResp.IsSuccessStatusCode)
                {
                    anyDeleted = true;
                    LogInfo($"  Deleted existing asset: {match.Name} (id {match.Id})");
                }
                else
                {
                    LogInfo($"  Could not delete asset {match.Name}: HTTP {(int)delResp.StatusCode}");
                }
            }
            catch (Exception ex)
            {
                LogInfo($"  Exception while deleting asset {match.Name}: {ex.Message}");
            }
        }

        return anyDeleted;
    }

    // ── Logging ─────────────────────────────────────────────────

    public event EventHandler<string>? LogMessage;

    private void LogInfo(string msg) => LogMessage?.Invoke(this, $"[INFO] {msg}");
    private void LogError(string msg) => LogMessage?.Invoke(this, $"[ERROR] {msg}");

    // ── Helpers ─────────────────────────────────────────────────

    private static string FormatBytes(long bytes) => bytes switch
    {
        >= 1_048_576 => $"{bytes / 1_048_576.0:F1} MB",
        >= 1024      => $"{bytes / 1024.0:F1} KB",
        _            => $"{bytes} B"
    };

    private string EnsureChangeEvaluationReport(
        (string PackageName, string Version, string ZipPath, string ManifestPath, string Platform, string Arch, string ChangeEvaluationPath) package,
        bool forceRegenerate = false)
    {
        if (!forceRegenerate && !string.IsNullOrWhiteSpace(package.ChangeEvaluationPath) && File.Exists(package.ChangeEvaluationPath))
            return package.ChangeEvaluationPath;

        LogInfo(forceRegenerate
            ? "Regenerating change evaluation report for current build..."
            : "Change evaluation report missing; generating source comparison for AI release notes...");
        var generated = ChangeEvaluator.Evaluate(
            _repoRoot,
            package.PackageName,
            package.Version,
            package.ManifestPath,
            _config.Changelog);

        return generated ?? package.ChangeEvaluationPath ?? "";
    }

    private static bool ReleaseBodyMatchesVersion(string body, string version)
    {
        if (string.IsNullOrWhiteSpace(body) || string.IsNullOrWhiteSpace(version))
            return false;
        return body.Contains(version, StringComparison.OrdinalIgnoreCase) ||
               body.Contains($"v{version}", StringComparison.OrdinalIgnoreCase);
    }

    private static string BuildFallbackReleaseBody(
        string version,
        IEnumerable<(string PackageName, string Version, string ZipPath, string ManifestPath, string Platform, string Arch, string ChangeEvaluationPath)> packages)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# Release v{version}");
        sb.AppendLine();
        sb.AppendLine("## What's Changed");
        sb.AppendLine("- AI release-note generation was unavailable, so no automatic source summary was produced.");
        sb.AppendLine("- Review the attached build artifacts and generated change evaluation report before publishing.");
        sb.AppendLine();
        sb.AppendLine("## Packaging");
        foreach (var p in packages)
            sb.AppendLine($"- `{p.PackageName}` ({p.Platform}/{p.Arch})");
        return sb.ToString().Trim();
    }

    // ── GitHub API response models ──────────────────────────────

    private class GitHubRelease
    {
        [JsonPropertyName("id")]          public long   Id        { get; set; }
        [JsonPropertyName("tag_name")]    public string TagName   { get; set; } = "";
        [JsonPropertyName("name")]        public string Name      { get; set; } = "";
        [JsonPropertyName("html_url")]    public string HtmlUrl   { get; set; } = "";
        [JsonPropertyName("upload_url")]  public string UploadUrl { get; set; } = "";
    }

    private class GitHubAsset
    {
        [JsonPropertyName("id")]                    public long   Id                { get; set; }
        [JsonPropertyName("name")]                  public string Name              { get; set; } = "";
        [JsonPropertyName("browser_download_url")]  public string BrowserDownloadUrl { get; set; } = "";
    }
}
