<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>JundotLauncher</AssemblyName>
    <RootNamespace>JundotLauncher</RootNamespace>
    <StartupObject>JundotLauncher.Program</StartupObject>
    <ApplicationIcon />
    <!-- Ensure UTF-8 encoding for source files with CJK characters -->
    <Utf8Output>true</Utf8Output>
  </PropertyGroup>

</Project>
